version: '2'

services:


  eureka:
    build: discovery
    ports:
      - "8761:8761"


  mongo:
    image: mongo
    ports:
      - "27017:27017"


  pc:
      build: pc
      ports:
        - '8081:8080'
      depends_on:
        - eureka
        - mongo
      environment:
        SPRING_DATA_MONGODB_HOST: mongo
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
        SERVICE_URL_DEFAULT_ZONE: 'http://eureka:8761/eureka/'


  po:
      build: po
      ports:
        - '8082:8080'
      links:
        - eureka
        - mongo
      environment:
        SPRING_DATA_MONGODB_HOST: mongo
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
        SERVICE_URL_DEFAULT_ZONE: 'http://eureka:8761/eureka/'


networks:
    default:
        driver: bridge
