version: '2'

services:

  config:
    build: config
    ports:
      - "8888:8888"


  discovery:
    build: discovery
    ports:
      - "8761:8761"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
    depends_on:
      - config

  mongo:
    image: mongo


  gateway:
    build: gateway
    ports:
      - '80:8080'
    depends_on:
      - discovery
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SERVICE_URL_DEFAULT_ZONE: http://discovery:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config:8888


  pc:
    build: pc
    ports:
      - '8081:8080'
    depends_on:
      - discovery
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SERVICE_URL_DEFAULT_ZONE: http://discovery:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config:8888


  po:
      build: po
      ports:
        - '8082:8080'
      links:
        - discovery
        - mongo
      environment:
        SPRING_DATA_MONGODB_HOST: mongo
        EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
        SERVICE_URL_DEFAULT_ZONE: http://discovery:8761/eureka/
        SPRING_CLOUD_CONFIG_URI: http://config:8888


networks:
    default:
        driver: bridge
