server:
  port: 8080


spring:
  application:
    name: gateway


zuul:
  routes:
    pc:
      serviceId: pc
      path: /pc/*
      stripPrefix: true
    po:
      serviceId: po
      path: /po/*
      stripPrefix: true